import type { Scene, Material, Escenografia, Person, Noticia } from '../types';
import { seedSheet } from '../api/sheetsClient';
import { SCENE_COLORS } from './constants';

const SEED_SCENES: Scene[] = [
  {
    id: 'scene-1',
    numero: 1,
    nombre: 'Dibujame unos patines',
    subtitulo: 'El joven estrella',
    descripcion: 'Teodoro llega al consultorio del Dr. Principe. El lugar es sobrio y gris, pero poco a poco se transforma en algo mas colorido. Transicion de lo serio a lo fantasioso. El Dr. Principe analiza a Teodoro y por medio de ejercicios de dibujo comienza a descubrir su problema.',
    personajes: 'Teodoro, Dr. Principe, Publico (rompe cuarta pared al final)',
    conflicto: 'Teodoro no disfruta el patinaje como antes, se siente frustrado por la ejecucion de su rutina y la presion le ha provocado apatia.',
    objetivos: 'El publico conoce la motivacion del protagonista. Introduccion al tono absurdo de la obra.',
    lineaEntrada: 'No me sale el movimiento',
    lineaConflicto: 'Es que tienes que probar esta nueva terapia (dibujos)',
    lineaSalida: 'Sale por la puerta y rompe la cuarta pared',
    juego: 'Interpretacion de dibujos',
    parodia: '',
    imagenUrl: 'https://psicologodecanini.com/wp-content/uploads/2022/01/psicoterapia.jpg.webp',
    color: SCENE_COLORS[0],
    acto: 'Acto 1. La Tierra',
    lugar: 'Salon Chico Vekio',
  },
  {
    id: 'scene-2',
    numero: 2,
    nombre: 'El pirata y el mapa',
    subtitulo: 'El Capitan Nereo',
    descripcion: 'Estamos en el mar. El Capitan Nereo es un pirata ridiculo, carismatico y obsesivo con el control que habita solitario un planeta lleno de islas y mares. Tiene una relacion estrecha con su fiel acompanante Neron, un gracioso perico parlanchin. Desea comandar una tripulacion para buscar con su mapa un gran tesoro.',
    personajes: 'Capitan Nereo, Teodoro, Dr. Principe, Baobab 1, 2 y 3, Publico',
    conflicto: 'Deseo de control. Quiere comandar cada movimiento y cada accion de su tripulacion, sin tener exito.',
    objetivos: 'Trabajar la amistad y la delegacion de tareas en equipo. Aceptar que se necesita ayuda.',
    lineaEntrada: '',
    lineaConflicto: '',
    lineaSalida: '',
    juego: 'Simon dice',
    parodia: 'Politico',
    imagenUrl: 'https://www.lavanguardia.com/files/image_990_484/files/fp/uploads/2021/03/11/604a0199e4d24.r_d.457-306.jpeg',
    color: SCENE_COLORS[1],
    acto: 'Acto 2. El Mundo Fantastico',
    lugar: 'Salon Verde Vekio',
  },
  {
    id: 'scene-3',
    numero: 3,
    nombre: 'El vanidoso y la lupa',
    subtitulo: 'Dylan, el Vanidoso',
    descripcion: 'Dylan es excentrico, diva y convenenciero. Fan de si mismo, busca ser eternamente admirado. Representa el deseo de admiracion. Quiere ser el centro de atencion y recibir constantemente validacion. Cuando pierde el foco, busca desesperadamente tenerlo de vuelta. Aparecen los Baobabs y se llevan la rosa.',
    personajes: 'El Vanidoso, Teodoro, Dr. Principe, Baobab 2 y 3, Publico',
    conflicto: 'La vanidad y la preocupacion constante por la apariencia. Los Baobabs logran robar la rosa.',
    objetivos: 'Teodoro ve reflejada su obsesion por que su peinado, maquillaje y vestuario esten en orden.',
    lineaEntrada: '',
    lineaConflicto: '',
    lineaSalida: '',
    juego: 'Descubre el mensaje a traves de la lupa',
    parodia: 'Influencer',
    imagenUrl: 'https://media.mdzol.com/p/b2456a2fa49799d1ee54cc4b11ed54cf/adjuntos/373/imagenes/001/163/0001163718/760x0/smart/problemente-es-el-antagonista-mas-carismatico-las-peliculas-animadas-foto-archivo.jpg',
    color: SCENE_COLORS[2],
    acto: 'Acto 2. El Mundo Fantastico',
    lugar: 'Salon Negro Vekio (esquina derecha)',
  },
  {
    id: 'scene-4',
    numero: 4,
    nombre: 'La geografa y el lapiz',
    subtitulo: 'Agente Catalina',
    descripcion: 'Agente Catalina es comprometida con su trabajo de agente de viajes. Superficial, exagerada, dramatica y a veces un poco grosera. Tiene un punto debil por el Dr. Principe. Es de mente cerrada; logra cotizar los mejores viajes pero jamas ha salido de su escritorio. Tiene cambios de humor constantes.',
    personajes: 'La Geografa Catarina, Teodoro, Dr. Principe',
    conflicto: 'Falta de animo o entusiasmo para ir mas alla de lo establecido. Buscara planificar ante todo para prevenir cualquier escenario desfavorable.',
    objetivos: 'Teodoro ve su falta de improvisacion. Puede improvisar la segunda vez que se cae.',
    lineaEntrada: '',
    lineaConflicto: '',
    lineaSalida: '',
    juego: 'Proyeccion de cartas',
    parodia: 'Agente de viajes Disney',
    imagenUrl: 'https://imgmedia.larepublica.pe/850x501/larepublica/original/2022/04/13/62574872ea80e22fb84460de.webp',
    color: SCENE_COLORS[3],
    acto: 'Acto 2. El Mundo Fantastico',
    lugar: 'Salon Negro Vekio (esquina izquierda)',
  },
  {
    id: 'scene-5',
    numero: 5,
    nombre: 'El planeta de los constructores',
    subtitulo: 'Los Baobabs / Constructores',
    descripcion: 'Los Baobabs crean una identidad como Constructores en un planeta desertico. Realizan movimientos mecanicos y repetitivos en una obra en construccion sin sentido. Cada uno cuenta con un talento unico, pero no han podido despertar para reconocer lo ilogico de su rutina. Teodoro logra que se despierten y vuelvan a divertirse.',
    personajes: 'Baobabs/Constructores 1, 2 y 3, Teodoro, Dr. Principe, Publico',
    conflicto: 'La obra en construccion es un caos total. Perdida de conexion emocional. Son la ultima prueba para Teodoro.',
    objetivos: 'Constructor 1: caligrafia hermosa y dibujos. Constructor 2: voz majestuosa y canto. Constructor 3: rimas y versos. Dejan de atormentar a Teodoro y encuentran un proposito con su arte.',
    lineaEntrada: '',
    lineaConflicto: '',
    lineaSalida: '',
    juego: 'Baile',
    parodia: 'Linea 6 del metro MTY',
    imagenUrl: 'https://www.shutterstock.com/image-vector/construction-site-cartoon-scene-industrial-260nw-2658942637.jpg',
    color: SCENE_COLORS[4],
    acto: 'Acto 2. El Mundo Fantastico',
    lugar: 'Salon Verde Vekio',
  },
  {
    id: 'scene-6',
    numero: 6,
    nombre: 'El planeta del Principito',
    subtitulo: 'Reencuentro con el nino interior',
    descripcion: 'Teodoro llega al planeta del Principito representando que ya conecto con su nino interior. Despedida emotiva y fondo azul lleno de estrellas.',
    personajes: 'Teodoro, Dr. Principe, Publico',
    conflicto: 'Despedida y aceptacion. Recuperacion de la rosa.',
    objetivos: 'Teodoro reconecta con su pasion original por el patinaje.',
    lineaEntrada: '',
    lineaConflicto: '',
    lineaSalida: 'No te vayas a olvidar de tus heelys',
    juego: '',
    parodia: '',
    imagenUrl: 'https://i0.wp.com/xavieh.com/wp-content/uploads/2016/04/FB2.jpg?resize=1024%2C667&ssl=1',
    color: SCENE_COLORS[5],
    acto: 'Acto 3. El Mundo Interior',
    lugar: 'Salon Negro Vekio',
  },
];

const SEED_MATERIALS: Material[] = [
  { id: 'mat-1', escenaId: 'scene-1', nombre: 'Bata de medico', cantidad: 1, estado: 'pendiente', responsableId: '', notas: 'Para Carlos L' },
  { id: 'mat-2', escenaId: 'scene-1', nombre: 'Camisa con rayas y mono grande contrastante', cantidad: 1, estado: 'pendiente', responsableId: '', notas: '' },
  { id: 'mat-3', escenaId: 'scene-1', nombre: 'Hojas y papeles', cantidad: 20, estado: 'pendiente', responsableId: '', notas: 'Para dibujos' },
  { id: 'mat-4', escenaId: 'scene-1', nombre: 'Plumones', cantidad: 10, estado: 'pendiente', responsableId: '', notas: '' },
  { id: 'mat-5', escenaId: 'scene-1', nombre: 'Cinta para pegar', cantidad: 3, estado: 'pendiente', responsableId: '', notas: '' },
  { id: 'mat-6', escenaId: 'scene-1', nombre: 'Pintura fluorescente', cantidad: 2, estado: 'pendiente', responsableId: '', notas: 'Para dibujos en la cara del doc al apagar luces' },
  { id: 'mat-7', escenaId: 'scene-1', nombre: 'Coderas y rodilleras', cantidad: 1, estado: 'pendiente', responsableId: '', notas: 'Para Teodoro - patinador' },
  { id: 'mat-8', escenaId: 'scene-1', nombre: 'Patineta', cantidad: 1, estado: 'pendiente', responsableId: '', notas: 'Prop de Teodoro' },
  { id: 'mat-9', escenaId: 'scene-1', nombre: 'Casco', cantidad: 1, estado: 'pendiente', responsableId: '', notas: 'Para Teodoro' },
  { id: 'mat-10', escenaId: 'scene-2', nombre: 'Bandera de pirata', cantidad: 1, estado: 'pendiente', responsableId: '', notas: '' },
  { id: 'mat-11', escenaId: 'scene-2', nombre: 'Maquina de humo', cantidad: 1, estado: 'pendiente', responsableId: '', notas: '' },
  { id: 'mat-12', escenaId: 'scene-2', nombre: 'Licras llamativas tipo Deadpool', cantidad: 3, estado: 'pendiente', responsableId: '', notas: 'Para los Baobabs' },
  { id: 'mat-13', escenaId: 'scene-2', nombre: 'Luces de color azul extras', cantidad: 4, estado: 'pendiente', responsableId: '', notas: 'Para escena de congelados' },
  { id: 'mat-14', escenaId: 'scene-2', nombre: 'Fomi y celofan', cantidad: 5, estado: 'pendiente', responsableId: '', notas: 'Para ambientar barco' },
  { id: 'mat-15', escenaId: 'scene-2', nombre: 'Pescados decorativos', cantidad: 10, estado: 'pendiente', responsableId: '', notas: 'Para el piso' },
  { id: 'mat-16', escenaId: 'scene-2', nombre: 'Pintura para espejos/vidrios', cantidad: 2, estado: 'pendiente', responsableId: '', notas: 'Para ambientar' },
  { id: 'mat-17', escenaId: 'scene-3', nombre: 'Espejos', cantidad: 3, estado: 'pendiente', responsableId: '', notas: '' },
  { id: 'mat-18', escenaId: 'scene-3', nombre: 'Imagenes impresas de caras', cantidad: 5, estado: 'pendiente', responsableId: '', notas: 'Caras de mujer/hombre' },
  { id: 'mat-19', escenaId: 'scene-3', nombre: 'Lona "Ella es lo mas increible del mundo"', cantidad: 1, estado: 'pendiente', responsableId: '', notas: '' },
  { id: 'mat-20', escenaId: 'scene-3', nombre: 'Lupa grande', cantidad: 1, estado: 'pendiente', responsableId: '', notas: 'Para el juego de la lupa' },
  { id: 'mat-21', escenaId: 'scene-4', nombre: 'Escritorio de agente de viajes', cantidad: 1, estado: 'pendiente', responsableId: '', notas: '' },
  { id: 'mat-22', escenaId: 'scene-4', nombre: 'Cartas/postales para proyeccion', cantidad: 10, estado: 'pendiente', responsableId: '', notas: 'Para el juego de proyeccion de cartas' },
  { id: 'mat-23', escenaId: 'scene-5', nombre: 'Bloques de construccion (utileria)', cantidad: 10, estado: 'pendiente', responsableId: '', notas: 'Para la obra en construccion' },
  { id: 'mat-24', escenaId: 'scene-5', nombre: 'Cascos de construccion', cantidad: 3, estado: 'pendiente', responsableId: '', notas: 'Para los constructores' },
  { id: 'mat-25', escenaId: 'scene-5', nombre: 'Libreta y lapiz', cantidad: 3, estado: 'pendiente', responsableId: '', notas: 'Para los constructores' },
  { id: 'mat-26', escenaId: 'scene-6', nombre: 'Tela azul con estrellas', cantidad: 1, estado: 'pendiente', responsableId: '', notas: 'Fondo del planeta del Principito' },
];

const SEED_ESCENOGRAFIA: Escenografia[] = [
  { id: 'esc-1', escenaId: 'scene-1', nombre: '2 sillas de consultorio', descripcion: 'Sillas para el consultorio del Dr.', estado: 'pendiente', responsableId: '' },
  { id: 'esc-2', escenaId: 'scene-1', nombre: 'Luces fluorescentes', descripcion: 'Transicion de lo gris a lo colorido. Al apagar, se ven los dibujos fluorescentes.', estado: 'pendiente', responsableId: '' },
  { id: 'esc-3', escenaId: 'scene-2', nombre: 'Proyector pared barco pirata', descripcion: 'Proyectar imagen de barco pirata en la pared', estado: 'pendiente', responsableId: '' },
  { id: 'esc-4', escenaId: 'scene-2', nombre: 'Ambientacion marina', descripcion: 'Fomi, celofan, pescados en el piso para simular el mar', estado: 'pendiente', responsableId: '' },
  { id: 'esc-5', escenaId: 'scene-3', nombre: 'Espejos y decoracion vanidoso', descripcion: 'Espejos e imagenes de caras para el planeta del vanidoso', estado: 'pendiente', responsableId: '' },
  { id: 'esc-6', escenaId: 'scene-4', nombre: 'Escritorio agente de viajes', descripcion: 'Escritorio de Catalina con mapas y folletos', estado: 'pendiente', responsableId: '' },
  { id: 'esc-7', escenaId: 'scene-5', nombre: 'Obra en construccion', descripcion: 'Bloques, pizarron de firmas, herramientas de construccion', estado: 'pendiente', responsableId: '' },
  { id: 'esc-8', escenaId: 'scene-6', nombre: 'Fondo azul con estrellas', descripcion: 'Fondo azul lleno de puntitos que asimilan estrellas', estado: 'pendiente', responsableId: '' },
];

const SEED_PEOPLE: Person[] = [
  { id: 'person-1', nombre: 'Carlos L', rol: 'Actor / Dr. Principe', contacto: '', activo: true },
  { id: 'person-2', nombre: 'Director', rol: 'Director', contacto: '', activo: true },
  { id: 'person-3', nombre: 'Staff 1', rol: 'Staff', contacto: '', activo: true },
  { id: 'person-4', nombre: 'Staff 2', rol: 'Staff', contacto: '', activo: true },
  { id: 'person-5', nombre: 'Actor Teodoro', rol: 'Actor / Teodoro', contacto: '', activo: true },
  { id: 'person-6', nombre: 'Actor Capitan Nereo', rol: 'Actor / Capitan Nereo', contacto: '', activo: true },
  { id: 'person-7', nombre: 'Actor Dylan/Vanidoso', rol: 'Actor / El Vanidoso', contacto: '', activo: true },
  { id: 'person-8', nombre: 'Actriz Catalina', rol: 'Actriz / Agente Catalina', contacto: '', activo: true },
  { id: 'person-9', nombre: 'Actor Baobab 1', rol: 'Actor / Baobab-Constructor 1', contacto: '', activo: true },
  { id: 'person-10', nombre: 'Actor Baobab 2', rol: 'Actor / Baobab-Constructor 2', contacto: '', activo: true },
  { id: 'person-11', nombre: 'Actor Baobab 3', rol: 'Actor / Baobab-Constructor 3', contacto: '', activo: true },
];

const SEED_NOTICIAS: Noticia[] = [
  {
    id: 'noticia-1',
    titulo: 'Audiciones y Reunion de Produccion',
    contenido: 'Audiciones este Jueves 26 de Marzo y Reunion de Produccion',
    fechaCreacion: new Date().toISOString(),
    activa: true,
  },
];

export async function seedAllData(): Promise<void> {
  await seedSheet('Escenas', SEED_SCENES as unknown as Record<string, unknown>[]);
  await seedSheet('Materiales', SEED_MATERIALS as unknown as Record<string, unknown>[]);
  await seedSheet('Escenografia', SEED_ESCENOGRAFIA as unknown as Record<string, unknown>[]);
  await seedSheet('Personas', SEED_PEOPLE as unknown as Record<string, unknown>[]);
  await seedSheet('Noticias', SEED_NOTICIAS as unknown as Record<string, unknown>[]);
  await seedSheet('Notas', []);
  await seedSheet('Chat', []);
  await seedSheet('Asignaciones', []);
}
